services:
  - type: web
    name: clicklogs-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false 
